cask_args appdir: '/Applications'

tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
brew 'coreutils'
brew 'file-formula'
brew 'git'
brew 'gh'
brew 'grc'
brew 'nvm'
brew 'syncthing', restart_service: true
brew 'terminal-notifier'
brew 'wget'
brew 'yarn'
cask 'alfred'
cask 'appcleaner'
cask 'atom'
cask 'bettertouchtool'
cask 'firefox'
cask 'google-chrome-canary'
cask 'google-chrome'
cask 'gpg-suite'
cask 'iterm2'
cask 'keepingyouawake'
cask 'postman'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'vlc'
