cask_args appdir: '/Applications'

tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'homebrew/services'
brew 'coreutils'
brew 'file-formula'
brew 'git'
brew 'gh'
brew 'grc'
brew 'volta'
brew 'btop'
brew 'terminal-notifier'
brew 'wget'
cask 'alfred'
cask 'appcleaner'
cask 'atom'
cask 'bettertouchtool'
cask 'gpg-suite'
cask 'iterm2'
cask 'keepingyouawake'
cask 'postman'
cask 'slack'
cask 'visual-studio-code'
cask 'vlc'
