cask_args appdir: '/Applications'

tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/dupes'

brew 'coreutils'
brew 'gist'
brew 'git'
brew 'grc'
brew 'hub'
brew 'openssl'
brew 'node'
brew 'terminal-notifier'
brew 'wget'
brew 'homebrew/dupes/file-formula'

cask 'appcleaner'
cask 'arduino'
cask 'atom'
cask 'bettertouchtool'
cask 'betterzipql'
cask 'caffeine'
cask 'diskmaker-x'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'google-hangouts'
cask 'gopro-studio'
cask 'gpgtools'
cask 'iterm2'
cask 'sequel-pro'
cask 'skype'
cask 'sourcetree'
cask 'sublime-text'
cask 'transmission'
cask 'virtualbox'
cask 'vlc'
