[settings]
trusted_config_paths = ["~/Code", "~/Code/Work"]

[tools]
bat = "latest"
chezmoi = "latest"
difftastic = "latest"
fd = "latest"
gh = "latest"
node = "lts"
pnpm = "latest"
ripgrep = "latest"
starship = "latest"
