"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](mauve)\
$os\
$battery\
[](bg:red fg:mauve)\
$username\
[](bg:peach fg:red)\
$directory\
[](bg:yellow fg:peach)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$c\
$golang\
$java\
$nodejs\
$php\
$rust\
[](fg:green bg:sapphire)\
$docker_context\
[ ](fg:sapphire)\
$line_break\
$container\
$hostname\
$sudo\
$cmd_duration\
$character"""

# allow git commands to run for the prompt
command_timeout = 1000
palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:mauve fg:crust"

[os.symbols]
Alpine = ""
Debian = "󰣚"
Linux = "󰌽"
Macos = "󰀵"
Ubuntu = "󰕈"

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user ]($style)'

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = "󰇚 "
"Music" = "󰝚 "
"Pictures" = "󰋩 "
"Code" = "󰲋 "

[git_branch]
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:crust bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:crust bg:yellow)]($style)'

[c]
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[golang]
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[java]
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[nodejs]
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[php]
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[docker_context]
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[battery]
full_symbol = '󰁹'
charging_symbol = '󰂄'
discharging_symbol = '󰁽'
unknown_symbol = '󰂃'
empty_symbol = '󰂎'
format = '[ $symbol$percentage ](fg:crust bg:mauve)'

[[battery.display]]
threshold = 101
style = "fg:crust bg:mauve"

[line_break]
disabled = false

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:lavender"
disabled = false
show_notifications = false
min_time_to_notify = 45000

[container]
style = "bg:lavender fg:crust"
format = "[](lavender)[$symbol $name]($style)[ ](fg:lavender)"

[hostname]
ssh_symbol = "󰢹 "
style = "bg:lavender fg:crust"
format = "[](lavender)[$ssh_symbol$hostname]($style)[ ](fg:lavender)"

[sudo]
disabled = false
style = "bg:lavender fg:crust"
format = "[](lavender)[$symbol]($style)[ ](fg:lavender)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
